name: Scrape UNICEF

on:
  schedule:
    - cron: "45 18 * * *"
  workflow_dispatch: {}

jobs:
  call:
    uses: ./.github/workflows/scrape.yml
    with:
      module: scrapers.unicef
    secrets: inherit